name: "First action"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "update-src"
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - src/**
            lib:
              - lib/**
      - name: check
        run: |
          echo '${{ toJSON(steps.filter.outputs) }}'
      - name: upload base ref info
        run: |
          if [[ '${{ github.event_name }}' == 'push' ]]; then
            BASE=${{ github.event.before }}
            ORIGINAL_REF=${{ github.ref }}
          elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            BASE=${{ github.base_ref }}
            ORIGINAL_REF=${{ github.head_ref }}
          fi
          echo $BASE > ref-base.txt
          echo $ORIGINAL_REF > ref-original.txt
          cat ref-base.txt
          cat ref-original.txt
          echo '${{ toJSON(github) }}'
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: ref-base
          path: |
            ref-base.txt
            ref-original.txt
          retention-days: 1
