name: "Second action"
on:
  workflow_run:
    workflows: ["First action"]
    types: [completed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a single artifact
        uses: dawidd6/action-download-artifact@v2
        id: download
        with:
          workflow: first-action.yml
          name: ref-base
          workflow_conclusion: success
          path: ./
      - shell: bash
        run: |
          ls -la
          echo '${{ toJSON(steps.download.outputs.artifacts) }}'
          cat '${{ steps.download.outputs.download-path }}'
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ steps.download.outputs.download-path }}
          filters: |
            src:
              - src/**
            lib:
              - lib/**
      - name: check
        run: |
          echo '${{ toJSON(steps.filter.outputs) }}'
